[project]
name = "toylora"
version = "0.1.0"
description = "a toy to show how lora works"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.8.0",
    "torchvision>=0.20.0",
    "numpy>=1.24.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.11",
]
